apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: ${CLICKHOUSE_USER}
      defaultDatabase: ${ANALYTICS_CLICKHOUSE_DATABASE}
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
